apiVersion: skaffold/v2alpha3
kind: Config 
deploy: 
    kubectl: 
        manifests: 
            - ./infra/k8s/*
build: 
    local: 
        push: false 
    artifacts:
        - image: nhatnguyen1810/auth 
          context: auth
          docker: 
            dockerfile: Dockerfile
          sync: 
            manual: 
                - src: 'src/**/*.ts'
                  dest: .
        - image: nhatnguyen1810/client 
          context: client
          docker: 
            dockerfile: Dockerfile
          sync: 
            manual: 
                - src: '**/*.js'
                  dest: .

        - image: nhatnguyen1810/tickets 
          context: tickets
          docker: 
            dockerfile: Dockerfile
          sync: 
            manual: 
                - src: 'src/**/*.ts'
                  dest: .
        - image: nhatnguyen1810/orders 
          context: orders
          docker: 
            dockerfile: Dockerfile
          sync: 
            manual: 
                - src: 'src/**/*.ts'
                  dest: .
        - image: nhatnguyen1810/expiration 
          context: expiration
          docker: 
            dockerfile: Dockerfile
          sync: 
            manual: 
                - src: 'src/**/*.ts'
                  dest: .
        - image: stephengrider/payments
          context: payments
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: 'src/**/*.ts'
                dest: .
              